### ISSUE TITLE
On startup: nonexistent property "padLevels" then pagePark terminates on call for index.md

### ISSUE THREAD

**Issue by sbwaters** [scripting/pagePark#27]
I realize Dave is occupied elsewhere but others may identify an issue. npm suggested using --trace-warnings for detail:

pagePark starts. I can port scan 1339. When I try to read localhost:1339 I can no longer portscan 1339.

Last login: Sat Dec 18 22:17:09 on ttys000
[sbwMacbookPro:~] sbw% cd /Users/sbw/Documents/pagePark-master 
[sbwMacbookPro:~/Documents/pagePark-master] sbw% node --trace-warnings pagepark.js
(node:48471) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.exports.setLevels (/Users/sbw/Documents/pagePark-master/node_modules/winston/lib/winston/common.js:32:14)
    at Object.<anonymous> (/Users/sbw/Documents/pagePark-master/node_modules/winston/lib/winston.js:83:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

PagePark v0.8.26 running on port 1339.

pageParkPackage v0.4.38. config == {
    "minuteToRunHourlyScripts": 0,
    "hourToRunOvernightScripts": 0,
    "scriptsFolderPath": "prefs/scripts/",
    "localStoragePath": "prefs/localStorage.json",
    "portToStartAllocating": 1670,
    "maxLogFileSize": 102400,
    "defaultMaxRestarts": 1000000,
    "defaultSilent": true,
    "myPort": 1339,
    "flWebsocketEnabled": false,
    "websocketPort": 1340,
    "indexFilename": "index",
    "flProcessScriptFiles": false,
    "extScriptFiles": "js",
    "flProcessMarkdownFiles": true,
    "extMarkdownFiles": "md",
    "flProcessOpmlFiles": true,
    "extOpmlFiles": "opml",
    "error404File": "prefs/error.html",
    "legalPathChars": "",
    "flCacheTemplatesLocally": false,
    "urlDefaultMarkdownTemplate": "http://scripting.com/code/pagepark/templates/markdown/template.txt",
    "urlDefaultOpmlTemplate": "http://scripting.com/code/pagepark/templates/opml/template.txt",
    "urlDefaultErrorPage": "http://scripting.com/code/pagepark/prefs/error.html",
    "flUnicasePaths": false,
    "defaultType": "text/html",
    "flHiddenFilesCheck": true,
    "ctGithubCacheSecs": 3600,
    "flRunChronologicalScripts": false,
    "flRunPersistentScripts": false,
    "flCliPortEnabled": false,
    "cliPort": 1349,
    "defaultDomanFolderName": "default",
    "defaultExtension": "",
    "flServeConfigJson": false
}

startup: __dirname == /Users/sbw/Documents/pagePark-master
startup: pageparkPrefs == {
    "myPort": 1339,
    "flWebsocketEnabled": false,
    "websocketPort": 1340,
    "indexFilename": "index",
    "flProcessScriptFiles": false,
    "extScriptFiles": "js",
    "flProcessMarkdownFiles": true,
    "extMarkdownFiles": "md",
    "flProcessOpmlFiles": true,
    "extOpmlFiles": "opml",
    "error404File": "prefs/error.html",
    "legalPathChars": "",
    "flCacheTemplatesLocally": false,
    "urlDefaultMarkdownTemplate": "http://scripting.com/code/pagepark/templates/markdown/template.txt",
    "urlDefaultOpmlTemplate": "http://scripting.com/code/pagepark/templates/opml/template.txt",
    "urlDefaultErrorPage": "http://scripting.com/code/pagepark/prefs/error.html",
    "flUnicasePaths": false,
    "defaultType": "text/html",
    "flHiddenFilesCheck": true,
    "ctGithubCacheSecs": 3600,
    "flRunChronologicalScripts": false,
    "flRunPersistentScripts": false,
    "flCliPortEnabled": false,
    "cliPort": 1349,
    "defaultDomanFolderName": "default",
    "defaultExtension": "",
    "flServeConfigJson": false
}

githubpub v0.5.64

Thnx.

**Comment by scripting** [comment]
Here's a bit of advice. 

I've installed PP following those directions as recently as last week. Quite a few times. I've never encountered anything like this situation. You should start over. And carefully follow the instructions. And write down everything you do. And if this happens again, you'll have the steps to reproduce. 

And I care as much about PP as any of my software.

**Comment by sbwaters** [comment]
Thank you. Will do.
Curious: What MacOS and node.js do you operate on?
Mine: MacOS: Big Sur 11.3.1,   node.js: v16.13.1
